language: python
python:
  - "3.6"

cache: pip
install:
  - pip install -r requirements.txt
  - pip install --editable . 
  - pip install halo

script: plugins/install_all.sh

jobs:
  include:
    - stage: Testing
      name: "Testing Configuration Commands"
      script:
       - pytest
   
    - stages:
      name: "Deploying to Development"
      if: branch = development
      script:
        - echo $TRAVIS_COMMIT