language: python
python:
  - "3.6"

cache: pip
install:
  - pip install -r requirements.txt
  - pip install --editable . 
  - pip install halo
  - cd plugins && bash install_all.sh && cd ..

jobs:
  include:
    # - stage: Installing plugins
    #   name: "Install Plugins"
    #   script:
    #    - cd plugins
    #    - bash install_all.sh
    #    - cd ..

    - stage: Running Unit Tests 
      name: "Unit Tests"
      script:
        - pytest

    - stage: Deploy
      name: "Deploying to Development"
      if: branch = development
      script:
        - echo $TRAVIS_COMMIT