name: raven
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - libedit=3.1.20181209
  - libffi=3.2.1
  - ncurses=6.1
  - openssl=1.1.1a
  - pip=19.0.1
  - python=3.6.8
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - click==7.0
    - click-plugins==1.0.4
    - delegator.py==0.1.1
    - future==0.17.1
    - pexpect==4.6.0
    - prompt-toolkit==1.0.15
    - ptyprocess==0.6.0
    - pygments==2.3.1
    - pyinquirer==1.0.3
    - regex==2019.2.21
    - six==1.12.0
    - wcwidth==0.1.7
    - whaaaaat==0.5.2
    - tqdm==4.31.1
prefix: /home/carson/anaconda3/envs/raven

